// ==UserScript==
// @name         DesignPlus Auto Formatter
// @namespace    http://canvas.newcastle.edu.au/
// @version      1
// @description  Formats document based on heading styles and simple input.
// @author       Paul Sijpkes
// @match        https://canvas.newcastle.edu.au/courses/*
// @grant        none
// ==/UserScript==

// @TODO change these to DOM nodes
const wrapper = `<div id="kl_wrapper_3" class="kl_uon kl_wrapper">[CONTENT]</div>`;
const header = `<div id='kl_banner'>
                        <h2><span id='kl_banner_left'>
                                <span class='kl_mod_num'>[WEEK_HEADING]</span> </span>
                            <span id='kl_banner_right'>
                                <span>[MODULE_HEADING]</span></h2>
                    </div>`;

const header_no_sub = `<div id='kl_banner'><h2><span id='kl_banner_right'>
                                <span>[MODULE_HEADING]</span>
                         </h2></div>`;

const verbose_block = ` <div id="[CIDI_ID]" class="">
        <h3><i class="[FONTA]" aria-hidden="true">
        <span class="dp-icon-content" style="display: none;">&nbsp;</span></i>[HEADING_TEXT]</h3>
        [CONTENT_HTML]
    </div>`

const custom_block = `<div id="[CUSTOM_ID]" class="">[CONTENT_HTML]</div>`

const part_header = `<div id='kl_banner'>[CONTENT_HTML]</div>`

const block = `<div id="kl_content_block_[n]" class="">[Generic_text]</div>`;

const moduleProgressCompletion = function(node) {
    const div = document.createElement('DIV')
    const p = document.createElement('P')
    div.id='kl_content_block_5'

    p.classList.add('kl_module_progress_completion')
    p.style.display = 'none'
    p.textContent = 'Module Item Completion (built in browser, hidden in app)'
    div.append(p)

    //for later.. node.append(div)
    return div;
};

// this list generated by ChatGPT
const validTags = [
    'A',
    'ABBR',
    'ADDRESS',
    'ARTICLE',
    'ASIDE',
    'B',
    'BDI',
    'BDO',
    'BLOCKQUOTE',
    'BODY',
    'BR',
    'BUTTON',
    'CAPTION',
    'CITE',
    'CODE',
    'COL',
    'COLGROUP',
    'DATA',
    'DATALIST',
    'DD',
    'DEL',
    'DETAILS',
    'DFN',
    'DIV',
    'DL',
    'DT',
    'EM',
    'EMBED',
    'FIELDSET',
    'FIGCAPTION',
    'FIGURE',
    'FOOTER',
    'FORM',
    'H1',
    'H2',
    'H3',
    'H4',
    'H5',
    'H6',
    'HEAD',
    'HEADER',
    'HGROUP',
    'HR',
    'HTML',
    'I',
    'IFRAME',
    'IMG',
    'INPUT',
    'INS',
    'KBD',
    'LABEL',
    'LEGEND',
    'LI',
    'LINK',
    'MAIN',
    'MAP',
    'MARK',
    'META',
    'METER',
    'NAV',
    'NOSCRIPT',
    'OBJECT',
    'OL',
    'OPTGROUP',
    'OPTION',
    'OUTPUT',
    'P',
    'PARAM',
    'PICTURE',
    'PRE',
    'PROGRESS',
    'Q',
    'RP',
    'RT',
    'RUBY',
    'S',
    'SAMP',
    'SCRIPT',
    'SECTION',
    'SELECT',
    'SLOT',
    'SMALL',
    'SOURCE',
    'STRONG',
    'STYLE',
    'SUB',
    'SUMMARY',
    'SUP',
    'TABLE',
    'TBODY',
    'TD',
    'TEMPLATE',
    'TEXTAREA',
    'TFOOT',
    'TH',
    'THEAD',
    'TIME',
    'TITLE',
    'TR',
    'TRACK',
    'U',
    'UL',
    'VAR',
    'VIDEO',
    'WBR'
];

// remember to concat 'fas ' to front of fonta value (if it exists)
const cidiLabTypes = { introduction : {id : 'kl_introduction', fonta: 'fa-book-reader' },
                      outcomes : {id : 'kl_objectives2', fonta: 'fa-check' },
                      readings : {id : 'kl_readings2', fonta: 'fa-book' },
                      references : {id: 'kl_content_block_7', fonta: 'fa-book-open'},
                      lecture_slides : {id : 'kl_lectures2', fonta: 'fa-chalkboard-teacher' },
                      lecture_videos : {id: 'kl_content_block_9', fonta: 'fa-play'},
                      watch : { id: 'kl_content_block_6', fonta: 'fa-play'},
                      activities : {id: 'kl_activities2', fonta: 'fa-edit'},
                      workshops : {id: 'kl_content_block_8', fonta: 'fa-tools'},
                      discussion : {id: 'kl_content_block_10', fonta: 'fa-comments'},
                      additional_resources : {id: 'kl_content_block_0', fonta: 'fa-paperclip'},
                      links : {id: 'kl_content_block_4', fonta: 'fa-link'},
                      assignments : {id: 'kl_assignments2', fonta: 'fa-pencil-alt'},
                      assignment : {id: 'kl_assignments2', fonta: 'fa-pencil-alt'},
                      quiz_description : {id: 'kl_content_block_1', fonta: 'fa-scroll'},
                      quiz_instructions : {id: 'kl_content_block_2', fonta: 'fa-tasks'},
                      generic_text : {id: 'kl_content_block_5', fonta: ''},
                      custom : {id: 'kl_custom_block_[n]', fonta: ''}
                     };

//const tinymce_elements = ["tinymce-parent-of-wiki_page_body", "tinymce-parent-of-assignment_description", "tinymce-parent-of-quiz_description"];

const statusbar_elements = ["quiz_description_statusbar", "wiki_page_body_statusbar", "assignment_description_statusbar"]

function findElement(_doc, ids) {
    let element

    for(let id of ids) {
        element = _doc.getElementById(id);
        if(element) break;
    }

    return element
}

(function () {
    'use strict';
    console.error("Auto format loaded...");

    let /*_in = null,*/ editor = null, _c = 0;
    let _check = setInterval(function () {
        //console.log("Checking for element... ", _c++);
        if( ! editor ) {
            try {
                editor = window.tinymce.activeEditor
            } catch (e) {
                console.log("editor not ready")
            }

            if(_c > 30) {
                clearInterval(_check);
            }
        } else {
            clearInterval(_check);
            main();
            return;
        }
    }, 500);

    function main() {
        let str = window.location.href
        let arr = str.split('/');
        console.log(arr);
        let course_no = arr[4]

        const format_btn = document.createElement("A")
        format_btn.textContent = "+UON Style"
        format_btn.style.marginRight = '1rem'
        format_btn.style.cursor = 'pointer'

        const clear_btn = document.createElement("A")
        clear_btn.textContent = "-UON Style"
        clear_btn.style.cursor = 'pointer'
        clear_btn.style.marginRight = '1rem'

      /*  const index_btn = document.createElement("A")
        index_btn.textContent = "INX"
        index_btn.title = "Add index at cursor"
        index_btn.style.cursor = 'pointer'
        index_btn.style.marginRight = '1rem' */

        const status_bar = findElement(document, statusbar_elements)

        const first_button = status_bar.querySelector('button:nth-of-type(1)')

        first_button.parentElement.insertBefore(format_btn, first_button)
        first_button.parentElement.insertBefore(clear_btn, first_button)
      //  first_button.parentElement.insertBefore(index_btn, first_button)

        const lookupCidiID = function(text) {
            if(!text) return null;

            const str = text.trim().toLowerCase().replace(' ', '_')

            for(const [key, value] of Object.entries(cidiLabTypes)) {
                if(key === str) {
                    return value;
                }
            }

            return null;
        };

        function addIndex(par) {

            let editorDoc = Object.hasOwn(editor, 'contentDocument') ? editor.contentDocument : null
            const h3s = editorDoc.getElementsByTagName("H3")

            let _na, _a, name, index_li, _newo, a_names = [];

            const index_ul = editorDoc.createElement("UL")

            Array.from(h3s).forEach((o, i) => {
                _na = editorDoc.createElement("A")
                _a = editorDoc.createElement("A")
                name = `${i}_uon_ps_list`
                _a.href = `#${name}`
                _a.textContent = o.textContent
                _na.name = name

                _newo = o.cloneNode(true)

                _newo.appendChild(_na)

               // _newo.style.backgroundColor = 'red'
              //  _newo.style.color = 'green'
                a_names[i] = _newo;
                //console.log(_newo, _newo.textContent)

               // o.parentElement.insertBefore(_newo, o)
                index_li = document.createElement("LI")
                index_li.appendChild(_a)
                index_ul.appendChild(index_li)
            })

            par.appendChild(index_ul)
            return a_names
        }

        format_btn.addEventListener("mouseup", function (e) {
            e.preventDefault()
            e.stopPropagation()

            let editorDoc = Object.hasOwn(editor, 'contentDocument') ? editor.contentDocument : null
            let kl_wrapper_3 = editorDoc ? editorDoc.getElementById('kl_wrapper_3') : null
            const title = findElement(document, ['title', 'assignment_name', 'quiz_title']).value

            try {
                let str = '', str2 = '', i = 0, outerHTML = "", formatterTag = false, last_h3_val = '', custom_blocks = 0, a_names = null;

                const childElsLen = editorDoc.body.children.length

                Array.from(editorDoc.body.children).forEach((par, x) => {

                    if(par && par.textContent.trim() === '###') {

                        if(par.previousSibling) {

                            if(par.previousSibling.previousSibling) {
                                str = header.replace(/\[WEEK_HEADING\]/gi, par.previousSibling.previousSibling.textContent.trim())
                            }

                            str = str ? str.replace(/\[MODULE_HEADING\]/gi, par.previousSibling.textContent.trim())
                                  : header_no_sub.replace(/\[MODULE_HEADING\]/gi, par.previousSibling.textContent.trim())

                        } else {
                            //str = header.replace(/\[WEEK_HEADING\]/gi, 'Sub Title')
                            str = header_no_sub.replace(/\[MODULE_HEADING\]/gi, title || 'Main Title')
                        }

                        outerHTML = "";
                        formatterTag = true;
                    }

                    if(par && par.textContent.trim() === '***') {
                        // model others on this later to avoid using strings
                        str += moduleProgressCompletion().outerHTML;

                        outerHTML = "";
                        formatterTag = true;
                    }

                    if(par && (par.textContent.trim() === '[index]')) {
                         par.textContent = null
                         a_names = addIndex(par)
                    }

                    if(par && (par.textContent.trim() === '---' || x === childElsLen-1 )) {

                        let cidi = lookupCidiID(last_h3_val)

                        formatterTag = (par.textContent.trim() === '---')

                        if(cidi) {
                            str2 = verbose_block.replace(/\[HEADING_TEXT\]/gi, last_h3_val)
                            str2 = str2.replace(/\[CIDI_ID\]/gi, cidi.id)
                            str2 = str2.replace(/\[FONTA\]/gi, `fas ${cidi.fonta}`)
                            str2 = str2.replace(/\[CONTENT_HTML\]/gi, outerHTML ? outerHTML : par.outerHTML)
                            str2 = str2.replace(/\[n\]/gi, i)
                        } else {
                            cidi = lookupCidiID('custom')

                            if(last_h3_val) {

                                outerHTML = outerHTML ? `<h3>${last_h3_val}</h3>` + outerHTML : par.outerHTML
                            }

                            const inc_id = cidi.id.replace(/\[n\]/gi, custom_blocks++)

                            str2 = custom_block.replace(/\[CUSTOM_ID\]/gi, inc_id)

                            str2 = str2.replace(/\[CONTENT_HTML\]/gi, outerHTML ? outerHTML : par.outerHTML)
                        }

                        str += str2

                        outerHTML = "";
                        last_h3_val = '';
                    }

                    if(!formatterTag) {
                      //  console.log(x, '---', par.textContent)
                        if(par.tagName === 'H3') { // h3 is reserved for block headers
                            last_h3_val = par.textContent.trim()
                            if(x == childElsLen-1) str += `<h3>${last_h3_val}</h3>`
                        } else {
                          //  console.log('ohtml ', par.outerHTML, 'ihtml ', par.innerHTML, 't ', par.textContent)
                            outerHTML += par.outerHTML
                            if(x == childElsLen-1) str += outerHTML
                        }
                    }

                    formatterTag = false;
                });

                let newStr

                if(kl_wrapper_3) {
                    kl_wrapper_3.innerHTML = str
                } else {
                    const p = str.indexOf('kl_wrapper_3')
                   // console.error(">!!>!!>!!>000>>>!!!>> ", p);

                    if(str.indexOf('kl_wrapper_3') == -1) {
                        str = wrapper.replace(/\[CONTENT\]/gi, str)
                    }

                    editor.setContent(str)

                    // add named anchor tags for any index
                    if(a_names.length) {
                        const h3s = editorDoc.getElementsByTagName("H3")
                        Array.from(h3s).forEach((o, i) => {
                            console.log(o, a_names[i])
                            o.replaceWith(a_names[i])
                        })
                    }
                }

            } catch (e) {
                console.error(e)
            }

            return false; // stop form submission
        })

        let html_str = '', _inblock = false, _inbanner = false, _ib = 0;

        function simplify(tag) {
            let p;
            let originTag = tag

            if(!tag) {
               // console.log("tag was null")
                return false;
            }

            if(tag.children) {
                // strip out all DIVs
                for(let c of tag.children) {

                    if(c.tagName === 'DIV') {

                        if(c.id === "kl_banner") {
                            c.append(addBannerDivider())
                        } else if(c.firstElementChild.classList.contains('kl_module_progress_completion')) {

                            c.append(addModuleProgressCompletion())
                            c.removeChild(c.firstElementChild)
                        } else {
                            c.append(addBlockDivider())
                        }

                        c.replaceWith(...c.childNodes)

                    }
                    if(c.children.length > 0) {
                        simplify(c)
                    }
                }
                // strip out all SPANs
                for(let c of tag.children) {

                    if(c.tagName === 'SPAN') {
                        c.replaceWith(...c.childNodes)
                    }

                }

                for(let c of originTag.children) {

                    if(validTags.indexOf(c.tagName.toUpperCase()) === -1) {

                        if(c.textContent.trim().length > 0) {
                            console.log("replacing with a P")
                            p = document.createElement("p")
                            c.parentElement.append(p)
                            p.textContent = c.textContent
                            c.replaceWith(p)
                        } else {
                            c.parentElement.removeChild(c)
                        }
                    }

                    if(c.children.length > 0) {
                        simplify(c)
                    }

                }
            }

            return tag
        }

        const addBannerDivider = function() {
            let p = document.createElement('p')
            p.textContent = '###'

            return p;
        }

        const addBlockDivider = function() {
            let p = document.createElement('p')
            p.textContent = '---'

            return p;
        }

        const addModuleProgressCompletion = function() {
            let p = document.createElement('p')
            p.textContent = '***'

            return p;
        }

        function removeDIVs(tag) {
            html_str += simplify(tag).innerHTML
        }

        clear_btn.addEventListener("mouseup", function (e) {
            e.preventDefault()
            e.stopPropagation()

            let editorDoc = Object.hasOwn(editor, 'contentDocument') ? editor.contentDocument : null
            let kl_wrapper_3 = editorDoc ? editorDoc.getElementById('kl_wrapper_3') : null

            const div = editorDoc.getElementById("kl_wrapper_3") || editorDoc.body

            html_str = ''
            removeDIVs(div)

            editor.setContent(html_str)
            return false; // stop form submission
        })

    }

})();